name: Build and Deploy Portfolio

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Generate short SHA
      id: sha
      run: echo "SHORT_SHA=$(echo $GITHUB_SHA | head -c 7)" >> $GITHUB_ENV

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: |
          kratagya121/portfolio:latest
          kratagya121/portfolio:${{ env.SHORT_SHA }}
        cache-from: type=registry,ref=kratagya121/portfolio:latest
        cache-to: type=inline

    - name: Configure Git
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "github-actions@github.com"

    - name: Update deployment file
      run: |
        sed -i "s|kratagya121/portfolio:.*|kratagya121/portfolio:${{ env.SHORT_SHA }}|g" k8s/deployment.yaml

    - name: Commit and push changes
      run: |
        git fetch origin main
        if git rev-list HEAD..origin/main --quiet; then
          cp k8s/deployment.yaml /tmp/deployment.yaml
          git reset --hard origin/main
          cp /tmp/deployment.yaml k8s/deployment.yaml
        fi
        git add k8s/deployment.yaml
        git commit -m "Update image tag to ${{ env.SHORT_SHA }}"
        git remote set-url origin https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }}
        git push origin main

  deploy-to-kubernetes:
    needs: build-and-push
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: main

    - name: Install ArgoCD CLI
      run: |
        curl -sSL -o argocd-linux-amd64 https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
        sudo install -m 555 argocd-linux-amd64 /usr/local/bin/argocd
        rm argocd-linux-amd64

    - name: Login to ArgoCD
      run: |
        argocd login localhost:8080 --username admin --password ${{ secrets.ARGOCD_PASSWORD }} --insecure

    - name: Sync ArgoCD Application
      run: |
        # Check if application exists
        if argocd app get portfolio &>/dev/null; then
          echo "Application exists, syncing..."
          argocd app sync portfolio --force
        else
          echo "Creating new application..."
          argocd app create portfolio \
            --repo https://github.com/kratagyanamdevv/my-portfolio.git \
            --path k8s \
            --dest-server https://kubernetes.default.svc \
            --dest-namespace default \
            --sync-policy automated
        fi
        
        # Wait for sync to complete
        argocd app wait portfolio --timeout 30
